# Generated by Django 5.0.6 on 2024-12-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterials',
            name='category',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Notes', 'Notes'), ('Others', 'Others'), ('Project Report', 'Project Report')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
