# Generated by Django 5.0.6 on 2024-12-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_studymaterials_course_studymaterials_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MCA', 'MCA'), ('BCA', 'BCA'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('B.Com', 'B.Com'), ('M.Com', 'M.Com'), ('B.A', 'B.A'), ('M.A', 'M.A'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='studymaterials',
            name='stream',
            field=models.CharField(choices=[('Civil', 'Civil'), ('Taxation', 'Taxation'), ('AI', 'AI'), ('General', 'General'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Computer Science', 'Computer Science'), ('Electronics', 'Electronics'), ('Chemical', 'Chemical'), ('Biotechnology', 'Biotechnology'), ('Others', 'Others')], max_length=100),
        ),
    ]
