# Generated by Django 5.0.6 on 2025-01-10 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_courses_classes_for_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes_for_course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='study.courses'),
        ),
    ]
