# Generated by Django 5.0.6 on 2024-12-19 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MCA', 'MCA'), ('BCA', 'BCA'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('B.Sc', 'B.Sc'), ('M.Sc', 'M.Sc'), ('B.Com', 'B.Com'), ('M.Com', 'M.Com'), ('B.A', 'B.A'), ('M.A', 'M.A')], max_length=100)),
                ('stream', models.CharField(choices=[('Civil', 'Civil'), ('Taxation', 'Taxation'), ('AI', 'AI'), ('General', 'General'), ('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Computer Science', 'Computer Science'), ('Electronics', 'Electronics'), ('Chemical', 'Chemical'), ('Biotechnology', 'Biotechnology')], max_length=100)),
                ('student_roll', models.CharField(max_length=100)),
                ('student_dob', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
